#!/bin/bash


#add getops() -q
#case
#    q)
#        ;;
#esac

function capColor() {
    TEXT=$1
    gum style --foreground "#118DFF" "$TEXT"
}

function redColor() {
    TEXT=$1
    gum style --foreground "#D82C20" "$TEXT"
}


gum style \
    --border double \
    --padding "1" \
    "Capacity Databases"

while getopts 'q' OPTION; do
    case "$OPTION" in
        q)
    echo "Choose $(redColor "permission") level $(capColor "for query")"
    TYPE=$(gum choose "readOnly" "dba")
    DATABASE=$(gum filter < ~/scripts/sqlQuery/dbList.md)
    ~/scripts/sqlQuery/$TYPE/$DATABASE
            ;;
        *)
            echo "Invalid flag"
            exit 1
            ;;
    esac
done

echo "Choose $(redColor "permission") level"
TYPE=$(gum choose "readOnly" "dba")
DATABASE=$(gum filter < ~/scripts/sqlLog/dbList.md)

~/scripts/sqlLog/$TYPE/$DATABASE
