#!/bin/bash

ns=notify-send
dmenu='dmenu -m 0 -fn VictorMono:size=20 -nf green -nb black -nf green -sb black'
dun='dunstify -h int:value:'

#LIST=$(kubectl get node | awk '{print $1}' | fzf --layout reverse)

#kubectl describe node ${LIST}
kubectl describe node $(~/scripts/nodeDescriber.sh) 
   if [ "$?" -eq 0 ]; then
       ${dun} "SELCTED!"
   else
       dunstify -u critical "No Node Selected"
       exit 1
   fi


#kubectl describe node ${list}
