#!/bin/bash

dmenu='dmenu -m 0 -fn VictorMono:size=20 -nf green -nb black -nf green -sb black'
dun='dunstify -h int:value:'

LIST=$(kubectl get svc -A | awk '{print $1 ,  $2}' | fzf --layout reverse)

kubectl describe svc -n ${LIST}
   if [ "$?" -eq 0 ]; then
       ${dun} "Service Found!"
   else
       dunstify -u critical "No Service Selected"
       exit 1
   fi

# use xargs to populate 'Found' message
#kubectl describe node ${list}
