#!/bin/bash

ns=notify-send
dmenu='dmenu -m 0 -fn VictorMono:size=20 -nf green -nb black -nf green -sb black'
dun='dunstify -h int:value:'
kubectl delete pod -n $(kubectl get pod -A | fzf --layout reverse | awk '{print $1, $2}')
