#!/bin/bash

ns=notify-send
dmenu='dmenu -m 0 -fn VictorMono:size=20 -nf green -nb black -nf green -sb black'
dun='dunstify -h int:value:'

LIST=$(cat ~/helmInfo/nodeTypeList.md |fzf --layout reverse)

kubectl get node --selector type=${LIST} -o wide
   if [ "$?" -eq 0 ]; then
       ${dun} "SELCTED!"
   else
       dunstify -u critical "No Node Selected"
       exit 1
   fi


#kubectl describe node ${list}
